<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-09-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee'),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee'),
        ),
    ]
=======
# Generated by Django 3.2.5 on 2021-09-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee'),
        ),
        migrations.AddField(
            model_name='work_experience',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee'),
        ),
    ]
>>>>>>> origin/hrms-09-02-2022
