# Generated by Django 3.2.5 on 2021-09-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_organization_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_files',
            name='file',
            field=models.FileField(max_length=254, upload_to=''),
        ),
    ]
