# Generated by Django 3.2.5 on 2021-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_organization_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_files',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
