# Generated by Django 3.2.5 on 2021-09-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_organization_files_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_files',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
