<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-10-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_announcement_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
=======
# Generated by Django 3.2.5 on 2021-10-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_announcement_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
>>>>>>> origin/hrms-09-02-2022
