<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-10-22 15:00

import app.models.travel_request_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_reporting_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_Expense_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
            options={
                'db_table': 'travel_expense_details',
            },
        ),
        migrations.CreateModel(
            name='Travel_Request_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_id', models.CharField(db_column='travel_id', default=app.models.travel_request_model.Travel_Request_Detail.generate_pk, max_length=20, unique=True)),
                ('place_of_visit', models.CharField(blank=True, max_length=130, null=True)),
                ('employee_department', models.CharField(blank=True, max_length=30, null=True)),
                ('expected_date_of_arrival', models.DateField(blank=True, null=True)),
                ('expected_date_of_depature', models.DateField(blank=True, null=True)),
                ('expected_duration_days', models.CharField(blank=True, max_length=30, null=True)),
                ('purpose_of_visit', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('billable_to_customer', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
            options={
                'db_table': 'travel_request_details',
            },
        ),
        migrations.CreateModel(
            name='Travel_Expense_More_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=180, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('ticket', models.CharField(blank=True, max_length=180, null=True)),
                ('lodging', models.CharField(blank=True, max_length=100, null=True)),
                ('boarding', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('local_conveyance', models.CharField(blank=True, max_length=100, null=True)),
                ('incidentals', models.CharField(blank=True, max_length=100, null=True)),
                ('others', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
                ('travel_exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.travel_expense_detail')),
            ],
            options={
                'db_table': 'travel_expense_more_details',
            },
        ),
        migrations.AddField(
            model_name='travel_expense_detail',
            name='travel',
            field=models.ForeignKey(blank=True, db_column='travel_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.travel_request_detail', to_field='travel_id'),
        ),
        migrations.CreateModel(
            name='Exit_Employee_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seperation_date', models.DateField(max_length=30)),
                ('Interviewer', models.CharField(max_length=30)),
                ('reason_leaving', models.TextField(blank=True, null=True)),
                ('rejoin_again', models.CharField(blank=True, max_length=50, null=True)),
                ('like_organi', models.CharField(blank=True, max_length=50, null=True)),
                ('improve_staff_welfare', models.TextField(blank=True, null=True)),
                ('share_with_us', models.TextField(blank=True, null=True)),
                ('vehicle_handled', models.CharField(blank=True, max_length=200, null=True)),
                ('equip_handled', models.CharField(blank=True, max_length=200, null=True)),
                ('library_book_submit', models.TextField(blank=True, null=True)),
                ('security', models.CharField(blank=True, max_length=200, null=True)),
                ('exit_interv_conduct', models.CharField(blank=True, max_length=200, null=True)),
                ('notice_period_follow', models.CharField(blank=True, max_length=200, null=True)),
                ('resignation_letter', models.CharField(blank=True, max_length=200, null=True)),
                ('manager_clearance', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
            options={
                'db_table': 'exit_employee_details',
            },
        ),
        migrations.CreateModel(
            name='Compoensatory_Request_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_date', models.DateField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=130, null=True)),
                ('duration', models.CharField(blank=True, max_length=30, null=True)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=450, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
            options={
                'db_table': 'compensatory_request_details',
            },
        ),
        migrations.CreateModel(
            name='Asset_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_asset', models.CharField(max_length=30)),
                ('given_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('asset_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
            options={
                'db_table': 'asset_details',
            },
        ),
    ]
=======
# Generated by Django 3.2.5 on 2021-10-22 15:00

import app.models.travel_request_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_reporting_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_Expense_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
            options={
                'db_table': 'travel_expense_details',
            },
        ),
        migrations.CreateModel(
            name='Travel_Request_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_id', models.CharField(db_column='travel_id', default=app.models.travel_request_model.Travel_Request_Detail.generate_pk, max_length=20, unique=True)),
                ('place_of_visit', models.CharField(blank=True, max_length=130, null=True)),
                ('employee_department', models.CharField(blank=True, max_length=30, null=True)),
                ('expected_date_of_arrival', models.DateField(blank=True, null=True)),
                ('expected_date_of_depature', models.DateField(blank=True, null=True)),
                ('expected_duration_days', models.CharField(blank=True, max_length=30, null=True)),
                ('purpose_of_visit', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('billable_to_customer', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
            options={
                'db_table': 'travel_request_details',
            },
        ),
        migrations.CreateModel(
            name='Travel_Expense_More_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=180, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('ticket', models.CharField(blank=True, max_length=180, null=True)),
                ('lodging', models.CharField(blank=True, max_length=100, null=True)),
                ('boarding', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('local_conveyance', models.CharField(blank=True, max_length=100, null=True)),
                ('incidentals', models.CharField(blank=True, max_length=100, null=True)),
                ('others', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
                ('travel_exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.travel_expense_detail')),
            ],
            options={
                'db_table': 'travel_expense_more_details',
            },
        ),
        migrations.AddField(
            model_name='travel_expense_detail',
            name='travel',
            field=models.ForeignKey(blank=True, db_column='travel_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.travel_request_detail', to_field='travel_id'),
        ),
        migrations.CreateModel(
            name='Exit_Employee_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seperation_date', models.DateField(max_length=30)),
                ('Interviewer', models.CharField(max_length=30)),
                ('reason_leaving', models.TextField(blank=True, null=True)),
                ('rejoin_again', models.CharField(blank=True, max_length=50, null=True)),
                ('like_organi', models.CharField(blank=True, max_length=50, null=True)),
                ('improve_staff_welfare', models.TextField(blank=True, null=True)),
                ('share_with_us', models.TextField(blank=True, null=True)),
                ('vehicle_handled', models.CharField(blank=True, max_length=200, null=True)),
                ('equip_handled', models.CharField(blank=True, max_length=200, null=True)),
                ('library_book_submit', models.TextField(blank=True, null=True)),
                ('security', models.CharField(blank=True, max_length=200, null=True)),
                ('exit_interv_conduct', models.CharField(blank=True, max_length=200, null=True)),
                ('notice_period_follow', models.CharField(blank=True, max_length=200, null=True)),
                ('resignation_letter', models.CharField(blank=True, max_length=200, null=True)),
                ('manager_clearance', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
            options={
                'db_table': 'exit_employee_details',
            },
        ),
        migrations.CreateModel(
            name='Compoensatory_Request_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_date', models.DateField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=130, null=True)),
                ('duration', models.CharField(blank=True, max_length=30, null=True)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=450, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
            options={
                'db_table': 'compensatory_request_details',
            },
        ),
        migrations.CreateModel(
            name='Asset_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_asset', models.CharField(max_length=30)),
                ('given_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('asset_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
            options={
                'db_table': 'asset_details',
            },
        ),
    ]
>>>>>>> origin/hrms-09-02-2022
