# Generated by Django 3.2.5 on 2021-10-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20211022_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='reporting_to',
        ),
    ]
