<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-10-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_employee_reporting_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reporting_to',
            new_name='Reporting',
        ),
    ]
=======
# Generated by Django 3.2.5 on 2021-10-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_employee_reporting_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reporting_to',
            new_name='Reporting',
        ),
    ]
>>>>>>> origin/hrms-09-02-2022
