<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-10-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_rename_reporting_to_reporting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('added_by', models.CharField(blank=True, max_length=30, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_starts_on', models.CharField(max_length=30)),
                ('week_ends_on', models.CharField(max_length=30)),
                ('week_off', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'weekend',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('start_date', models.DateField(max_length=30)),
                ('end_date', models.DateField(max_length=30)),
                ('reminder', models.DateField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
=======
# Generated by Django 3.2.5 on 2021-10-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_rename_reporting_to_reporting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('added_by', models.CharField(blank=True, max_length=30, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_starts_on', models.CharField(max_length=30)),
                ('week_ends_on', models.CharField(max_length=30)),
                ('week_off', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'weekend',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('start_date', models.DateField(max_length=30)),
                ('end_date', models.DateField(max_length=30)),
                ('reminder', models.DateField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
>>>>>>> origin/hrms-09-02-2022
