<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-11-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_location_task_weekend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard_employee',
            name='photo_url',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
=======
# Generated by Django 3.2.5 on 2021-11-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_location_task_weekend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard_employee',
            name='photo_url',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
>>>>>>> origin/hrms-09-02-2022
