# Generated by Django 3.2.5 on 2021-11-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_onboard_employee_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emirate_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='onboard_employee',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='onboard_employee',
            name='emirate_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='onboard_employee',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
