# Generated by Django 3.2.5 on 2021-11-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20211102_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_balance',
            name='total_month',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
