<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-11-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_by_leave_request', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by_leave_request', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_id_leave_request', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_leave_request', to='app.employee'),
        ),
    ]
=======
# Generated by Django 3.2.5 on 2021-11-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_by_leave_request', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by_leave_request', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_id_leave_request', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_leave_request', to='app.employee'),
        ),
    ]
>>>>>>> origin/hrms-09-02-2022
