# Generated by Django 3.2.5 on 2021-11-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20211115_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoensatory_request_detail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_id_leave_request', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_type_id_request', to='app.leave_type'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='team_mailid',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
