<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-11-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_employee_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
=======
# Generated by Django 3.2.5 on 2021-11-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_employee_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
>>>>>>> origin/hrms-09-02-2022
