<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-11-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_employee_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoensatory_request_detail',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
=======
# Generated by Django 3.2.5 on 2021-11-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_employee_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoensatory_request_detail',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
>>>>>>> origin/hrms-09-02-2022
