# Generated by Django 3.2.5 on 2021-11-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_compoensatory_request_detail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoensatory_request_detail',
            name='compoensatory_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
