<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-11-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_compoensatory_request_detail_compoensatory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
=======
# Generated by Django 3.2.5 on 2021-11-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_compoensatory_request_detail_compoensatory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
>>>>>>> origin/hrms-09-02-2022
