# Generated by Django 3.2.5 on 2021-11-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_employee_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='document_url',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
