# Generated by Django 3.2.5 on 2021-12-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_leave_balance_total_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='subject',
            field=models.TextField(),
        ),
    ]
