# Generated by Django 3.2.5 on 2021-12-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20211217_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_wfh_approved',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
