# Generated by Django 3.2.5 on 2021-12-11 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_announcement_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='passport_exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='psssport_url',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_emp', to='app.location'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_id_leave_request', to='app.employee'),
        ),
    ]
