# Generated by Django 3.2.5 on 2021-12-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_attendance_is_wfh_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_wfh_approved',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
