# Generated by Django 3.2.5 on 2021-12-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_workhome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday_detail',
            name='applicable_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_location', to='app.location'),
        ),
    ]
