# Generated by Django 3.2.5 on 2021-12-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_vaccination_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination_detail',
            old_name='vaccin_phase',
            new_name='vaccin_name',
        ),
    ]
