# Generated by Django 3.2.5 on 2021-12-29 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_vaccination_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize_Leave_Effective',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_after', models.CharField(max_length=255)),
                ('effective_period', models.CharField(max_length=255)),
                ('effective_from_date', models.DateField(blank=True, null=True)),
                ('effective_from', models.CharField(max_length=255)),
                ('accrual', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('accrual_period', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_on', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_month', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_no_of_days', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('effective_in', models.CharField(blank=True, max_length=255, null=True)),
                ('reset', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('reset_period', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_on', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_month', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_carry_forward', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('reset_carry_count', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('reset_carry_method', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_carry_forward_max', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_carry_forward_overall_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_carry_encashment', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('reset_carry_enc_count', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('reset_carry_enc_method', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_encashment_forward_max', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_carry_forward_expiry_in', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('reset_carry_forward_expiry_month', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_balance', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('maximum_balance', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.leave_type')),
            ],
            options={
                'db_table': 'customize_leave_effective',
            },
        ),
    ]
