# Generated by Django 3.2.5 on 2021-12-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_customize_leave_effective'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday_detail',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
