# Generated by Django 3.2.5 on 2021-12-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_client_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_client',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_client', to='app.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_head', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_users', to='app.employee'),
        ),
    ]
