# Generated by Django 3.2.5 on 2021-12-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_auto_20211229_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('working_on', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelog_project', to='app.project')),
            ],
            options={
                'db_table': 'timelogs',
            },
        ),
    ]
