# Generated by Django 3.2.5 on 2021-12-30 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_holiday_detail_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=50)),
                ('mobile_number', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=12)),
                ('fax', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('pincode', models.CharField(max_length=12)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('company_size', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_users', models.CharField(max_length=255, null=True)),
                ('project_cost', models.CharField(max_length=30)),
                ('project_description', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
                ('project_client', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_client', to='app.client')),
                ('project_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_head', to='app.employee')),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to='app.employee')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='TimeLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('working_on', models.TextField(blank=True, null=True)),
                ('decription', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelog_employee', to='app.employee')),
                ('project', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelog_project', to='app.project')),
            ],
            options={
                'db_table': 'timelogs',
            },
        ),
    ]
