# Generated by Django 3.2.5 on 2021-12-29 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_timelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelogs',
            name='employee',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelog_employee', to='app.employee'),
        ),
    ]
