# Generated by Django 3.2.5 on 2021-12-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_timelogs_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelogs',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
