# Generated by Django 3.2.5 on 2022-01-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20220103_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_wfh_approved',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
