# Generated by Django 3.2.5 on 2022-01-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_attendance_is_wfh_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_wfh_approved',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
