# Generated by Django 3.2.5 on 2021-12-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_timelogs_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_users',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
