# Generated by Django 3.2.5 on 2022-01-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_alter_attendance_is_wfh_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_part',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
