# Generated by Django 3.2.5 on 2022-01-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_alter_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkin_active',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkout_active',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
