# Generated by Django 3.2.5 on 2022-01-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_alter_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_half',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
