# Generated by Django 3.2.5 on 2022-01-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
