# Generated by Django 3.2.5 on 2022-01-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_auto_20220105_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='checkin_actived',
            new_name='checkin_active',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='checkout_actived',
            new_name='checkout_active',
        ),
    ]
