# Generated by Django 3.2.5 on 2022-01-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_alter_employee_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkin_device',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkout_device',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='first_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
