# Generated by Django 3.2.5 on 2022-01-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_alter_employee_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='first_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
