# Generated by Django 3.2.5 on 2022-01-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20220128_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoensatory_request_detail',
            name='is_aproved',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compoensatory_request_detail',
            name='total_hours',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
