# Generated by Django 3.2.5 on 2022-01-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20220121_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkin_device',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkout_device',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
