# Generated by Django 3.2.5 on 2022-01-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20220106_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_part',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
