# Generated by Django 3.2.5 on 2022-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20220131_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='comp_off',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
