# Generated by Django 3.2.5 on 2022-01-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20220121_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoensatory_request_detail',
            name='is_aproved',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
