# Generated by Django 3.2.5 on 2022-01-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_compoensatory_request_detail_is_aproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoensatory_request_detail',
            name='total_hours',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
