# Generated by Django 3.2.5 on 2022-02-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_auto_20220205_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nick_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
