# Generated by Django 3.2.5 on 2022-02-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_auto_20220203_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoensatory_request_detail',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
