# Generated by Django 3.2.5 on 2022-02-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_excelfileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFileUpload',
        ),
    ]
