# Generated by Django 3.2.5 on 2022-02-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_leaverequest_reject_reason'),
        ('app', '0084_delete_excelfileupload'),
    ]

    operations = [
    ]
