# Generated by Django 3.2.5 on 2022-02-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_merge_20220218_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboard_employee',
            name='passport_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
