# Generated by Django 3.2.5 on 2022-02-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_onboard_employee_passport_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboard_employee',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee'),
        ),
        migrations.AddField(
            model_name='onboard_employee',
            name='business_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboard_employee',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboard_employee',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboard_employee',
            name='job_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboard_employee',
            name='joining_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboard_employee',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboard_employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
