# Generated by Django 3.2.5 on 2022-02-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_auto_20220221_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard_employee',
            name='joining_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
