# Generated by Django 3.2.5 on 2022-02-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_onboard_employee_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboard_employee',
            name='job_description',
            field=models.TextField(null=True),
        ),
    ]
