# Generated by Django 3.2.5 on 2022-02-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_onboard_employee_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboard_employee',
            name='offer_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
