# Generated by Django 3.2.5 on 2022-02-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_onboard_employee_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboard_employee',
            name='validity_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
