# Generated by Django 3.2.5 on 2022-02-28 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_onboard_employee_validity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboard_employee',
            name='acknowledgement',
            field=models.FileField(default=django.utils.timezone.now, max_length=254, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onboard_employee',
            name='company_policy',
            field=models.FileField(default=django.utils.timezone.now, max_length=254, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onboard_employee',
            name='cv',
            field=models.FileField(default=django.utils.timezone.now, max_length=254, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onboard_employee',
            name='other_documents',
            field=models.FileField(default=django.utils.timezone.now, max_length=254, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onboard_employee',
            name='passport_copy',
            field=models.FileField(default=django.utils.timezone.now, max_length=254, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onboard_employee',
            name='salary_components',
            field=models.TextField(null=True),
        ),
    ]
