# Generated by Django 3.2.5 on 2022-02-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_auto_20220228_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard_employee',
            name='acknowledgement',
            field=models.FileField(max_length=254, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='onboard_employee',
            name='company_policy',
            field=models.FileField(max_length=254, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='onboard_employee',
            name='cv',
            field=models.FileField(max_length=254, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='onboard_employee',
            name='other_documents',
            field=models.FileField(max_length=254, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='onboard_employee',
            name='passport_copy',
            field=models.FileField(max_length=254, null=True, upload_to=''),
        ),
    ]
