# Generated by Django 3.2.5 on 2022-03-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_auto_20220228_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_unit', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('added_by', models.CharField(blank=True, max_length=30, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='app.department')),
            ],
            options={
                'db_table': 'business_unit',
            },
        ),
    ]
