# Generated by Django 3.2.5 on 2022-03-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_business_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard_employee',
            name='business_unit',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_business_unit', to='app.business_unit'),
        ),
        migrations.AlterField(
            model_name='onboard_employee',
            name='company',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_dept', to='app.department'),
        ),
    ]
