# Generated by Django 3.2.5 on 2022-03-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_auto_20220303_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard_employee',
            name='acknowledgement',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='onboard_employee',
            name='company_policy',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='onboard_employee',
            name='cv',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='onboard_employee',
            name='other_documents',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='onboard_employee',
            name='passport_copy',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='onboard_employee',
            name='salary_components',
            field=models.TextField(blank=True, null=True),
        ),
    ]
