# Generated by Django 3.2.5 on 2022-03-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_variable_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable_salary',
            name='description',
            field=models.TextField(),
        ),
    ]
