# Generated by Django 3.2.5 on 2022-03-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_alter_variable_salary_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboard_employee',
            name='customize',
            field=models.TextField(blank=True, null=True),
        ),
    ]
