# Generated by Django 3.2.5 on 2022-03-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_onboard_employee_customize'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboard_employee',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
