# Generated by Django 3.2.5 on 2022-03-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_onboard_employee_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboard_employee',
            name='salary_description',
            field=models.TextField(null=True),
        ),
    ]
